### ISSUE TITLE
Plugin selecting wrong GPU

### ISSUE THREAD

**Issue by thatnovaguy** [b3rs3rk/gpustat-unraid#1]
Hello, I’m having a minor issue in that the plugin seems to only select one card and doesn’t display the cards correctly in the plug-in settings. Here's some [pics. ](https://imgur.com/a/MNQlvdt)

**Comment by b3rs3rk** [comment]
Plan is to add a detection to the Settings page allowing you to select the GPU you want monitored on the plugin page.  Will add to features to implement in next release.  I will tag the commit implementing it with this issue ID.

**Comment by SpartacusIam** [comment]
To picky back off this issue since it seems related, any chance of adding the ability to view All GPU stats in the dashboard, not just a specific one chosen from settings?

**Comment by b3rs3rk** [comment]
> 
> 
> To picky back off this issue since it seems related, any chance of adding the ability to view All GPUs stats in the dashboard, not just a specific one chosen from settings?

Yeah, not related at all except very minutely.  That's almost worthy of another development branch to be honest.
