### ISSUE TITLE
[BUG] - Session app icon size is abnormal

### ISSUE THREAD

**Issue by wyx1818** [b3rs3rk/gpustat-unraid#17]
**Describe the bug**
Session app icon size is abnormal

**To Reproduce**
1. Go to Dashboard

**Screenshots**
![image](https://user-images.githubusercontent.com/31715036/108590142-f2c4ac80-739c-11eb-9218-d1ef82649446.png)

**Client (please complete the following information):**
 - OS: MacOS 11.2.1 (20D74)
 - Browser chrome
 - Version 88.0.4324.182

**Server (please complete the following information):**
 - Device: Physical Server
 - OS Version: UnRAID v6.9.0-rc2
 - GPU:  NVIDIA GeForce GTX 965M

**Additional context**
DIsabled .gpu-image height can be resolved

**Comment by b3rs3rk** [comment]
Nice bug report!  Should be fixed once I author a new plugin version.
