### ISSUE TITLE
[ENHANCEMENT] - tdarr icon support

### ISSUE THREAD

**Issue by binarygeek119** [b3rs3rk/gpustat-unraid#19]
just add support of tdarr_aio (version 1) and tdarr + tdarr_node (version 2) icon for active apps

![tdarr (1)](https://user-images.githubusercontent.com/72405030/110221338-6680b200-7e91-11eb-9f65-9a05d7bb7ea1.png)

**Comment by b3rs3rk** [comment]
@binarygeek119 I need a sample of 'nvidia-smi -q -x -i 0' substituting the 0 for whatever GPU ID you're using in Tdarr.  In my searches, I've only seen HandbrakeCli running when Tdarr is actively using the GPU to encode/decode, which might be tough to distinguish from other containers.  Plex, for example, uses the 'Plex Transcoder' process which is easy.

**Comment by binarygeek119** [comment]
here is the output
`<?xml version="1.0" ?>
<!DOCTYPE nvidia_smi_log SYSTEM "nvsmi_device_v11.dtd">
<nvidia_smi_log>
        <timestamp>Sat Mar 13 05:26:00 2021</timestamp>
        <driver_version>460.56</driver_version>
        <cuda_version>11.2</cuda_version>
        <attached_gpus>1</attached_gpus>
        <gpu id="00000000:05:00.0">
                <product_name>GeForce GTX 950</product_name>
                <product_brand>GeForce</product_brand>
                <display_mode>Disabled</display_mode>
                <display_active>Disabled</display_active>
                <persistence_mode>Disabled</persistence_mode>
                <mig_mode>
                        <current_mig>N/A</current_mig>
                        <pending_mig>N/A</pending_mig>
                </mig_mode>
                <mig_devices>
                        None
                </mig_devices>
                <accounting_mode>Disabled</accounting_mode>
                <accounting_mode_buffer_size>4000</accounting_mode_buffer_size>
                <driver_model>
                        <current_dm>N/A</current_dm>
                        <pending_dm>N/A</pending_dm>
                </driver_model>
                <serial>N/A</serial>
                <uuid>GPU-0738929a-d4ff-aef4-0bf1-7d4bc7d6597f</uuid>
                <minor_number>0</minor_number>
                <vbios_version>84.06.3D.00.50</vbios_version>
                <multigpu_board>No</multigpu_board>
                <board_id>0x500</board_id>
                <gpu_part_number>N/A</gpu_part_number>
                <inforom_version>
                        <img_version>N/A</img_version>
                        <oem_object>N/A</oem_object>
                        <ecc_object>N/A</ecc_object>
                        <pwr_object>N/A</pwr_object>
                </inforom_version>
                <gpu_operation_mode>
                        <current_gom>N/A</current_gom>
                        <pending_gom>N/A</pending_gom>
                </gpu_operation_mode>
                <gpu_virtualization_mode>
                        <virtualization_mode>None</virtualization_mode>
                        <host_vgpu_mode>N/A</host_vgpu_mode>
                </gpu_virtualization_mode>
                <ibmnpu>
                        <relaxed_ordering_mode>N/A</relaxed_ordering_mode>
                </ibmnpu>
                <pci>
                        <pci_bus>05</pci_bus>
                        <pci_device>00</pci_device>
                        <pci_domain>0000</pci_domain>
                        <pci_device_id>140210DE</pci_device_id>
                        <pci_bus_id>00000000:05:00.0</pci_bus_id>
                        <pci_sub_system_id>29513842</pci_sub_system_id>
                        <pci_gpu_link_info>
                                <pcie_gen>
                                        <max_link_gen>2</max_link_gen>
                                        <current_link_gen>2</current_link_gen>
                                </pcie_gen>
                                <link_widths>
                                        <max_link_width>16x</max_link_width>
                                        <current_link_width>16x</current_link_width>
                                </link_widths>
                        </pci_gpu_link_info>
                        <pci_bridge_chip>
                                <bridge_chip_type>N/A</bridge_chip_type>
                                <bridge_chip_fw>N/A</bridge_chip_fw>
                        </pci_bridge_chip>
                        <replay_counter>0</replay_counter>
                        <replay_rollover_counter>0</replay_rollover_counter>
                        <tx_util>0 KB/s</tx_util>
                        <rx_util>0 KB/s</rx_util>
                </pci>
                <fan_speed>29 %</fan_speed>
                <performance_state>P0</performance_state>
                <clocks_throttle_reasons>
                        <clocks_throttle_reason_gpu_idle>Not Active</clocks_throttle_reason_gpu_idle>
                        <clocks_throttle_reason_applications_clocks_setting>Active</clocks_throttle_reason_applications_clocks_setting>
                        <clocks_throttle_reason_sw_power_cap>Not Active</clocks_throttle_reason_sw_power_cap>
                        <clocks_throttle_reason_hw_slowdown>Not Active</clocks_throttle_reason_hw_slowdown>
                        <clocks_throttle_reason_hw_thermal_slowdown>N/A</clocks_throttle_reason_hw_thermal_slowdown>
                        <clocks_throttle_reason_hw_power_brake_slowdown>N/A</clocks_throttle_reason_hw_power_brake_slowdown>
                        <clocks_throttle_reason_sync_boost>Not Active</clocks_throttle_reason_sync_boost>
                        <clocks_throttle_reason_sw_thermal_slowdown>Not Active</clocks_throttle_reason_sw_thermal_slowdown>
                        <clocks_throttle_reason_display_clocks_setting>Not Active</clocks_throttle_reason_display_clocks_setting>
                </clocks_throttle_reasons>
                <fb_memory_usage>
                        <total>2002 MiB</total>
                        <used>0 MiB</used>
                        <free>2002 MiB</free>
                </fb_memory_usage>
                <bar1_memory_usage>
                        <total>256 MiB</total>
                        <used>2 MiB</used>
                        <free>254 MiB</free>
                </bar1_memory_usage>
                <compute_mode>Default</compute_mode>
                <utilization>
                        <gpu_util>3 %</gpu_util>
                        <memory_util>0 %</memory_util>
                        <encoder_util>0 %</encoder_util>
                        <decoder_util>0 %</decoder_util>
                </utilization>
                <encoder_stats>
                        <session_count>0</session_count>
                        <average_fps>0</average_fps>
                        <average_latency>0</average_latency>
                </encoder_stats>
                <fbc_stats>
                        <session_count>0</session_count>
                        <average_fps>0</average_fps>
                        <average_latency>0</average_latency>
                </fbc_stats>
                <ecc_mode>
                        <current_ecc>N/A</current_ecc>
                        <pending_ecc>N/A</pending_ecc>
                </ecc_mode>
                <ecc_errors>
                        <volatile>
                                <single_bit>
                                        <device_memory>N/A</device_memory>
                                        <register_file>N/A</register_file>
                                        <l1_cache>N/A</l1_cache>
                                        <l2_cache>N/A</l2_cache>
                                        <texture_memory>N/A</texture_memory>
                                        <texture_shm>N/A</texture_shm>
                                        <cbu>N/A</cbu>
                                        <total>N/A</total>
                                </single_bit>
                                <double_bit>
                                        <device_memory>N/A</device_memory>
                                        <register_file>N/A</register_file>
                                        <l1_cache>N/A</l1_cache>
                                        <l2_cache>N/A</l2_cache>
                                        <texture_memory>N/A</texture_memory>
                                        <texture_shm>N/A</texture_shm>
                                        <cbu>N/A</cbu>
                                        <total>N/A</total>
                                </double_bit>
                        </volatile>
                        <aggregate>
                                <single_bit>
                                        <device_memory>N/A</device_memory>
                                        <register_file>N/A</register_file>
                                        <l1_cache>N/A</l1_cache>
                                        <l2_cache>N/A</l2_cache>
                                        <texture_memory>N/A</texture_memory>
                                        <texture_shm>N/A</texture_shm>
                                        <cbu>N/A</cbu>
                                        <total>N/A</total>
                                </single_bit>
                                <double_bit>
                                        <device_memory>N/A</device_memory>
                                        <register_file>N/A</register_file>
                                        <l1_cache>N/A</l1_cache>
                                        <l2_cache>N/A</l2_cache>
                                        <texture_memory>N/A</texture_memory>
                                        <texture_shm>N/A</texture_shm>
                                        <cbu>N/A</cbu>
                                        <total>N/A</total>
                                </double_bit>
                        </aggregate>
                </ecc_errors>
                <retired_pages>
                        <multiple_single_bit_retirement>
                                <retired_count>N/A</retired_count>
                                <retired_pagelist>N/A</retired_pagelist>
                        </multiple_single_bit_retirement>
                        <double_bit_retirement>
                                <retired_count>N/A</retired_count>
                                <retired_pagelist>N/A</retired_pagelist>
                        </double_bit_retirement>
                        <pending_blacklist>N/A</pending_blacklist>
                        <pending_retirement>N/A</pending_retirement>
                </retired_pages>
                <remapped_rows>N/A</remapped_rows>
                <temperature>
                        <gpu_temp>55 C</gpu_temp>
                        <gpu_temp_max_threshold>101 C</gpu_temp_max_threshold>
                        <gpu_temp_slow_threshold>96 C</gpu_temp_slow_threshold>
                        <gpu_temp_max_gpu_threshold>N/A</gpu_temp_max_gpu_threshold>
                        <gpu_target_temperature>80 C</gpu_target_temperature>
                        <memory_temp>N/A</memory_temp>
                        <gpu_temp_max_mem_threshold>N/A</gpu_temp_max_mem_threshold>
                </temperature>
                <supported_gpu_target_temp>
                        <gpu_target_temp_min>60 C</gpu_target_temp_min>
                        <gpu_target_temp_max>95 C</gpu_target_temp_max>
                </supported_gpu_target_temp>
                <power_readings>
                        <power_state>P0</power_state>
                        <power_management>Supported</power_management>
                        <power_draw>25.76 W</power_draw>
                        <power_limit>110.00 W</power_limit>
                        <default_power_limit>110.00 W</default_power_limit>
                        <enforced_power_limit>110.00 W</enforced_power_limit>
                        <min_power_limit>60.00 W</min_power_limit>
                        <max_power_limit>132.00 W</max_power_limit>
                </power_readings>
                <clocks>
                        <graphics_clock>1151 MHz</graphics_clock>
                        <sm_clock>1151 MHz</sm_clock>
                        <mem_clock>3304 MHz</mem_clock>
                        <video_clock>945 MHz</video_clock>
                </clocks>
                <applications_clocks>
                        <graphics_clock>1152 MHz</graphics_clock>
                        <mem_clock>3305 MHz</mem_clock>
                </applications_clocks>
                <default_applications_clocks>
                        <graphics_clock>1152 MHz</graphics_clock>
                        <mem_clock>3305 MHz</mem_clock>
                </default_applications_clocks>
                <max_clocks>
                        <graphics_clock>1519 MHz</graphics_clock>
                        <sm_clock>1519 MHz</sm_clock>
                        <mem_clock>3305 MHz</mem_clock>
                        <video_clock>1245 MHz</video_clock>
                </max_clocks>
                <max_customer_boost_clocks>
                        <graphics_clock>N/A</graphics_clock>
                </max_customer_boost_clocks>
                <clock_policy>
                        <auto_boost>N/A</auto_boost>
                        <auto_boost_default>N/A</auto_boost_default>
                </clock_policy>
                <supported_clocks>
                        <supported_mem_clock>
                                <value>3305 MHz</value>
                                <supported_graphics_clock>1519 MHz</supported_graphics_clock>
                                <supported_graphics_clock>1506 MHz</supported_graphics_clock>
                                <supported_graphics_clock>1493 MHz</supported_graphics_clock>
                                <supported_graphics_clock>1481 MHz</supported_graphics_clock>
                                <supported_graphics_clock>1468 MHz</supported_graphics_clock>
                                <supported_graphics_clock>1455 MHz</supported_graphics_clock>
                                <supported_graphics_clock>1443 MHz</supported_graphics_clock>
                                <supported_graphics_clock>1430 MHz</supported_graphics_clock>
                                <supported_graphics_clock>1418 MHz</supported_graphics_clock>
                                <supported_graphics_clock>1405 MHz</supported_graphics_clock>
                                <supported_graphics_clock>1392 MHz</supported_graphics_clock>
                                <supported_graphics_clock>1380 MHz</supported_graphics_clock>
                                <supported_graphics_clock>1367 MHz</supported_graphics_clock>
                                <supported_graphics_clock>1354 MHz</supported_graphics_clock>
                                <supported_graphics_clock>1342 MHz</supported_graphics_clock>
                                <supported_graphics_clock>1329 MHz</supported_graphics_clock>
                                <supported_graphics_clock>1316 MHz</supported_graphics_clock>
                                <supported_graphics_clock>1304 MHz</supported_graphics_clock>
                                <supported_graphics_clock>1291 MHz</supported_graphics_clock>
                                <supported_graphics_clock>1278 MHz</supported_graphics_clock>
                                <supported_graphics_clock>1266 MHz</supported_graphics_clock>
                                <supported_graphics_clock>1253 MHz</supported_graphics_clock>
                                <supported_graphics_clock>1240 MHz</supported_graphics_clock>
                                <supported_graphics_clock>1228 MHz</supported_graphics_clock>
                                <supported_graphics_clock>1215 MHz</supported_graphics_clock>
                                <supported_graphics_clock>1202 MHz</supported_graphics_clock>
                                <supported_graphics_clock>1190 MHz</supported_graphics_clock>
                                <supported_graphics_clock>1177 MHz</supported_graphics_clock>
                                <supported_graphics_clock>1164 MHz</supported_graphics_clock>
                                <supported_graphics_clock>1152 MHz</supported_graphics_clock>
                                <supported_graphics_clock>1139 MHz</supported_graphics_clock>
                                <supported_graphics_clock>1126 MHz</supported_graphics_clock>
                                <supported_graphics_clock>1114 MHz</supported_graphics_clock>
                                <supported_graphics_clock>1101 MHz</supported_graphics_clock>
                                <supported_graphics_clock>1088 MHz</supported_graphics_clock>
                                <supported_graphics_clock>1076 MHz</supported_graphics_clock>
                                <supported_graphics_clock>1063 MHz</supported_graphics_clock>
                                <supported_graphics_clock>1050 MHz</supported_graphics_clock>
                                <supported_graphics_clock>1038 MHz</supported_graphics_clock>
                                <supported_graphics_clock>1025 MHz</supported_graphics_clock>
                                <supported_graphics_clock>1013 MHz</supported_graphics_clock>
                                <supported_graphics_clock>1000 MHz</supported_graphics_clock>
                                <supported_graphics_clock>988 MHz</supported_graphics_clock>
                                <supported_graphics_clock>975 MHz</supported_graphics_clock>
                                <supported_graphics_clock>963 MHz</supported_graphics_clock>
                                <supported_graphics_clock>950 MHz</supported_graphics_clock>
                                <supported_graphics_clock>938 MHz</supported_graphics_clock>
                                <supported_graphics_clock>925 MHz</supported_graphics_clock>
                                <supported_graphics_clock>913 MHz</supported_graphics_clock>
                                <supported_graphics_clock>900 MHz</supported_graphics_clock>
                                <supported_graphics_clock>888 MHz</supported_graphics_clock>
                                <supported_graphics_clock>886 MHz</supported_graphics_clock>
                                <supported_graphics_clock>873 MHz</supported_graphics_clock>
                                <supported_graphics_clock>861 MHz</supported_graphics_clock>
                                <supported_graphics_clock>848 MHz</supported_graphics_clock>
                                <supported_graphics_clock>835 MHz</supported_graphics_clock>
                                <supported_graphics_clock>823 MHz</supported_graphics_clock>
                                <supported_graphics_clock>810 MHz</supported_graphics_clock>
                                <supported_graphics_clock>797 MHz</supported_graphics_clock>
                                <supported_graphics_clock>785 MHz</supported_graphics_clock>
                                <supported_graphics_clock>772 MHz</supported_graphics_clock>
                                <supported_graphics_clock>759 MHz</supported_graphics_clock>
                                <supported_graphics_clock>747 MHz</supported_graphics_clock>
                                <supported_graphics_clock>734 MHz</supported_graphics_clock>
                                <supported_graphics_clock>721 MHz</supported_graphics_clock>
                                <supported_graphics_clock>709 MHz</supported_graphics_clock>
                                <supported_graphics_clock>696 MHz</supported_graphics_clock>
                                <supported_graphics_clock>683 MHz</supported_graphics_clock>
                                <supported_graphics_clock>671 MHz</supported_graphics_clock>
                                <supported_graphics_clock>658 MHz</supported_graphics_clock>
                                <supported_graphics_clock>645 MHz</supported_graphics_clock>
                                <supported_graphics_clock>633 MHz</supported_graphics_clock>
                                <supported_graphics_clock>620 MHz</supported_graphics_clock>
                                <supported_graphics_clock>608 MHz</supported_graphics_clock>
                                <supported_graphics_clock>595 MHz</supported_graphics_clock>
                                <supported_graphics_clock>582 MHz</supported_graphics_clock>
                                <supported_graphics_clock>570 MHz</supported_graphics_clock>
                                <supported_graphics_clock>557 MHz</supported_graphics_clock>
                                <supported_graphics_clock>544 MHz</supported_graphics_clock>
                                <supported_graphics_clock>532 MHz</supported_graphics_clock>
                                <supported_graphics_clock>519 MHz</supported_graphics_clock>
                                <supported_graphics_clock>507 MHz</supported_graphics_clock>
                                <supported_graphics_clock>494 MHz</supported_graphics_clock>
                                <supported_graphics_clock>482 MHz</supported_graphics_clock>
                                <supported_graphics_clock>469 MHz</supported_graphics_clock>
                                <supported_graphics_clock>457 MHz</supported_graphics_clock>
                                <supported_graphics_clock>444 MHz</supported_graphics_clock>
                                <supported_graphics_clock>432 MHz</supported_graphics_clock>
                                <supported_graphics_clock>419 MHz</supported_graphics_clock>
                                <supported_graphics_clock>407 MHz</supported_graphics_clock>
                                <supported_graphics_clock>405 MHz</supported_graphics_clock>
                                <supported_graphics_clock>324 MHz</supported_graphics_clock>
                                <supported_graphics_clock>270 MHz</supported_graphics_clock>
                                <supported_graphics_clock>202 MHz</supported_graphics_clock>
                                <supported_graphics_clock>162 MHz</supported_graphics_clock>
                                <supported_graphics_clock>135 MHz</supported_graphics_clock>
                        </supported_mem_clock>
                        <supported_mem_clock>
                                <value>810 MHz</value>
                                <supported_graphics_clock>1519 MHz</supported_graphics_clock>
                                <supported_graphics_clock>1506 MHz</supported_graphics_clock>
                                <supported_graphics_clock>1493 MHz</supported_graphics_clock>
                                <supported_graphics_clock>1481 MHz</supported_graphics_clock>
                                <supported_graphics_clock>1468 MHz</supported_graphics_clock>
                                <supported_graphics_clock>1455 MHz</supported_graphics_clock>
                                <supported_graphics_clock>1443 MHz</supported_graphics_clock>
                                <supported_graphics_clock>1430 MHz</supported_graphics_clock>
                                <supported_graphics_clock>1418 MHz</supported_graphics_clock>
                                <supported_graphics_clock>1405 MHz</supported_graphics_clock>
                                <supported_graphics_clock>1392 MHz</supported_graphics_clock>
                                <supported_graphics_clock>1380 MHz</supported_graphics_clock>
                                <supported_graphics_clock>1367 MHz</supported_graphics_clock>
                                <supported_graphics_clock>1354 MHz</supported_graphics_clock>
                                <supported_graphics_clock>1342 MHz</supported_graphics_clock>
                                <supported_graphics_clock>1329 MHz</supported_graphics_clock>
                                <supported_graphics_clock>1316 MHz</supported_graphics_clock>
                                <supported_graphics_clock>1304 MHz</supported_graphics_clock>
                                <supported_graphics_clock>1291 MHz</supported_graphics_clock>
                                <supported_graphics_clock>1278 MHz</supported_graphics_clock>
                                <supported_graphics_clock>1266 MHz</supported_graphics_clock>
                                <supported_graphics_clock>1253 MHz</supported_graphics_clock>
                                <supported_graphics_clock>1240 MHz</supported_graphics_clock>
                                <supported_graphics_clock>1228 MHz</supported_graphics_clock>
                                <supported_graphics_clock>1215 MHz</supported_graphics_clock>
                                <supported_graphics_clock>1202 MHz</supported_graphics_clock>
                                <supported_graphics_clock>1190 MHz</supported_graphics_clock>
                                <supported_graphics_clock>1177 MHz</supported_graphics_clock>
                                <supported_graphics_clock>1164 MHz</supported_graphics_clock>
                                <supported_graphics_clock>1152 MHz</supported_graphics_clock>
                                <supported_graphics_clock>1139 MHz</supported_graphics_clock>
                                <supported_graphics_clock>1126 MHz</supported_graphics_clock>
                                <supported_graphics_clock>1114 MHz</supported_graphics_clock>
                                <supported_graphics_clock>1101 MHz</supported_graphics_clock>
                                <supported_graphics_clock>1088 MHz</supported_graphics_clock>
                                <supported_graphics_clock>1076 MHz</supported_graphics_clock>
                                <supported_graphics_clock>1063 MHz</supported_graphics_clock>
                                <supported_graphics_clock>1050 MHz</supported_graphics_clock>
                                <supported_graphics_clock>1038 MHz</supported_graphics_clock>
                                <supported_graphics_clock>1025 MHz</supported_graphics_clock>
                                <supported_graphics_clock>1013 MHz</supported_graphics_clock>
                                <supported_graphics_clock>1000 MHz</supported_graphics_clock>
                                <supported_graphics_clock>988 MHz</supported_graphics_clock>
                                <supported_graphics_clock>975 MHz</supported_graphics_clock>
                                <supported_graphics_clock>963 MHz</supported_graphics_clock>
                                <supported_graphics_clock>950 MHz</supported_graphics_clock>
                                <supported_graphics_clock>938 MHz</supported_graphics_clock>
                                <supported_graphics_clock>925 MHz</supported_graphics_clock>
                                <supported_graphics_clock>913 MHz</supported_graphics_clock>
                                <supported_graphics_clock>900 MHz</supported_graphics_clock>
                                <supported_graphics_clock>888 MHz</supported_graphics_clock>
                                <supported_graphics_clock>886 MHz</supported_graphics_clock>
                                <supported_graphics_clock>873 MHz</supported_graphics_clock>
                                <supported_graphics_clock>861 MHz</supported_graphics_clock>
                                <supported_graphics_clock>848 MHz</supported_graphics_clock>
                                <supported_graphics_clock>835 MHz</supported_graphics_clock>
                                <supported_graphics_clock>823 MHz</supported_graphics_clock>
                                <supported_graphics_clock>810 MHz</supported_graphics_clock>
                                <supported_graphics_clock>797 MHz</supported_graphics_clock>
                                <supported_graphics_clock>785 MHz</supported_graphics_clock>
                                <supported_graphics_clock>772 MHz</supported_graphics_clock>
                                <supported_graphics_clock>759 MHz</supported_graphics_clock>
                                <supported_graphics_clock>747 MHz</supported_graphics_clock>
                                <supported_graphics_clock>734 MHz</supported_graphics_clock>
                                <supported_graphics_clock>721 MHz</supported_graphics_clock>
                                <supported_graphics_clock>709 MHz</supported_graphics_clock>
                                <supported_graphics_clock>696 MHz</supported_graphics_clock>
                                <supported_graphics_clock>683 MHz</supported_graphics_clock>
                                <supported_graphics_clock>671 MHz</supported_graphics_clock>
                                <supported_graphics_clock>658 MHz</supported_graphics_clock>
                                <supported_graphics_clock>645 MHz</supported_graphics_clock>
                                <supported_graphics_clock>633 MHz</supported_graphics_clock>
                                <supported_graphics_clock>620 MHz</supported_graphics_clock>
                                <supported_graphics_clock>608 MHz</supported_graphics_clock>
                                <supported_graphics_clock>595 MHz</supported_graphics_clock>
                                <supported_graphics_clock>582 MHz</supported_graphics_clock>
                                <supported_graphics_clock>570 MHz</supported_graphics_clock>
                                <supported_graphics_clock>557 MHz</supported_graphics_clock>
                                <supported_graphics_clock>544 MHz</supported_graphics_clock>
                                <supported_graphics_clock>532 MHz</supported_graphics_clock>
                                <supported_graphics_clock>519 MHz</supported_graphics_clock>
                                <supported_graphics_clock>507 MHz</supported_graphics_clock>
                                <supported_graphics_clock>494 MHz</supported_graphics_clock>
                                <supported_graphics_clock>482 MHz</supported_graphics_clock>
                                <supported_graphics_clock>469 MHz</supported_graphics_clock>
                                <supported_graphics_clock>457 MHz</supported_graphics_clock>
                                <supported_graphics_clock>444 MHz</supported_graphics_clock>
                                <supported_graphics_clock>432 MHz</supported_graphics_clock>
                                <supported_graphics_clock>419 MHz</supported_graphics_clock>
                                <supported_graphics_clock>407 MHz</supported_graphics_clock>
                                <supported_graphics_clock>405 MHz</supported_graphics_clock>
                                <supported_graphics_clock>324 MHz</supported_graphics_clock>
                                <supported_graphics_clock>270 MHz</supported_graphics_clock>
                                <supported_graphics_clock>202 MHz</supported_graphics_clock>
                                <supported_graphics_clock>162 MHz</supported_graphics_clock>
                                <supported_graphics_clock>135 MHz</supported_graphics_clock>
                        </supported_mem_clock>
                        <supported_mem_clock>
                                <value>405 MHz</value>
                                <supported_graphics_clock>405 MHz</supported_graphics_clock>
                                <supported_graphics_clock>324 MHz</supported_graphics_clock>
                                <supported_graphics_clock>270 MHz</supported_graphics_clock>
                                <supported_graphics_clock>202 MHz</supported_graphics_clock>
                                <supported_graphics_clock>162 MHz</supported_graphics_clock>
                                <supported_graphics_clock>135 MHz</supported_graphics_clock>
                        </supported_mem_clock>
                </supported_clocks>
                <processes>
                </processes>
                <accounted_processes>
                </accounted_processes>
        </gpu>

</nvidia_smi_log>`

**Comment by b3rs3rk** [comment]
@binarygeek119 Okay, this is at least specific enough to the point where I can attribute ffmpeg processes to tdarr.  Do you know what the process name is in nvidia-smi when tdarr is using Handbrake?

**Comment by binarygeek119** [comment]
tdarr handbrake output
[output.txt](https://github.com/b3rs3rk/gpustat-unraid/files/6150802/output.txt)

**Comment by b3rs3rk** [comment]
@binarygeek119 Thanks.  Does HandbrakeCLI just call ffmpeg?  It appears that way from your output.  I think me already having added Handbrake will cover that part of it.  I'll try to add just ffmpeg as Tdarr.  It's a shame Tdarr doesn't run a specifically named process wrapper like Plex.
