### ISSUE TITLE
[ENHANCEMENT] - Add unmanic app detection

### ISSUE THREAD

**Issue by JaseNZC** [b3rs3rk/gpustat-unraid#24]
Possibly look at unmanic as a detected app when running.
[https://hub.docker.com/r/josh5/unmanic/tags?page=1&ordering=last_updated](url)

When looking at the process though it only seems to be identifying ffmpeg.

<img width="783" alt="Screen Shot 2021-03-22 at 4 44 54 PM" src="https://user-images.githubusercontent.com/64925341/111938488-f6c82380-8b2e-11eb-8bf0-d70605e9341e.png">

Was just an idea to look into. :-)

**Comment by b3rs3rk** [comment]
Unless we could lobby that the maintainer of that docker container change the ffmpeg binary/command path execution I won't be able to add the detection.  I just added tdarr and that calls both `ffmpeg` and `HandbrakeCLI` with no other identifiers.  So unmanic will likely show tdarr app usage when it is actively using the GPU as of right now.

**Comment by b3rs3rk** [comment]
@JaseNZC Try this when Unmanic is transcoding:

`echo $(ps -fp <insert_pid_from_nvidia-smi> -o command) `

So from your picture it would be:

`echo $(ps -fp 28089 -o command)`

You have to be quick in some cases.  The Plex Transcoder likes to spawn new processes each time the transcoder is throttled.  I doubt this will be a problem with Unmanic but you never know.

What I'm hoping is that there is unmanic specific stuff in the larger ffmpeg argument(s) that I can use.  Just paste me the result if you can.  Thanks.

**Comment by JaseNZC** [comment]
Hope this helps.
`root@box:~# echo $(ps -fp 29788 -o command)
COMMAND ffmpeg -hwaccel cuda -hwaccel_device 0 -i /input/5c8d7900b7573ed9dd9573fc/Extreme Public Piss #1.mpg -hide_banner -loglevel info -strict -2 -max_muxing_queue_size 512 -map 0:0 -map 0:1 -c:v:0 hevc_nvenc -c:a:0 aac -y /tmp/unmanic/unmanic_file_conversion-1616754474.6918821/Extreme Public Piss #1-1616754474.691891.mp4`

**Comment by b3rs3rk** [comment]
@JaseNZC does unmanic always use /tmp/unmanic or is this user configurable?

**Comment by JaseNZC** [comment]
Its not configurable that I can see anywhere.

**Comment by b3rs3rk** [comment]
Cool.  I think I have it worked out then.  I'll try to spawn an unmanic container and test it then I'll add a new release.  You don't by chance also have tdarr running and could do the same thing for that?  Meaning get me the extended command line output from it.

**Comment by JaseNZC** [comment]
Yeah sorry the whole idea of Unmanic was to go away from tdarr I find it much better for my needs :-)

**Comment by b3rs3rk** [comment]
I'm messing with Unmanic now.  Seems pretty simple and straightforward to use.

**Comment by JaseNZC** [comment]
Yeah set a directory(s) to watch and just let it run that is why I like it.

**Comment by b3rs3rk** [comment]
![image](https://user-images.githubusercontent.com/3584954/112751588-d53ac200-8f9c-11eb-85bc-b419eea20578.png)

**Comment by JaseNZC** [comment]
See easy as :-)
