### ISSUE TITLE
[ENHANCEMENT] - Incorrect icon on dashboard/include dizquetv icon on dashboard

### ISSUE THREAD

**Issue by ctrlaltd1337ed** [b3rs3rk/gpustat-unraid#25]
Using dizquetv w/ffmpeg to transcode files and it is showing up as Emby.

![image](https://user-images.githubusercontent.com/10511491/113964249-2054a080-97f9-11eb-8e29-c99c99244f4f.png)

![image](https://user-images.githubusercontent.com/10511491/113964419-79243900-97f9-11eb-8d82-c471d5434eb7.png)

DizqueTV icon

![image](https://user-images.githubusercontent.com/10511491/113964559-b4bf0300-97f9-11eb-8fe8-203532e4254b.png)

**Comment by b3rs3rk** [comment]
Yeah I was afraid this was going to start happening with all the apps that just call ffmpeg.  I'll see if I can find a transparent image of that to add to the detection.  Thanks for the report.

**Comment by b3rs3rk** [comment]
@ctrlaltd1337ed Try this when DizqueTV is using the GPU:

`echo $(ps -fp <insert_pid_from_nvidia-smi> -o command)`

So from your picture it would be:

`echo $(ps -fp 31837 -o command)`

You have to be quick in some cases. The Plex Transcoder likes to spawn new processes each time the transcoder is throttled. I doubt this will be a problem with DizqueTV but you never know.

I need this information to hopefully pinpoint when ffmpeg is being called specifically for disquetv and not some other application.

**Comment by ctrlaltd1337ed** [comment]
COMMAND /usr/bin/ffmpeg -threads 4 -fflags +genpts+discardcorrupt+igndts -re -ss 1062.772 -i PLEXURLTOMYMEDIAWASHERE -i http://192.168.2.53:8000/images/channels/25-seinfeld.png -filter_complex [0:v]null[video];[video]scale=1920:1080:flags=bicubic[scaled];[scaled]setsar=1[siz];[1:v]scale=192:-1[icn];[siz][icn]overlay=x=W-w-19:y=H-h-22[comb];[0:1]anull[audio];[audio]apad=whole_dur=243116ms[padded] -map [comb] -map [padded] -c:v h264_nvenc -flags cgop+ilme -sc_threshold 1000000000 -b:v 10000k -maxrate:v 10000k -bufsize:v 2000k -b:a 192k -maxrate:a 192k -bufsize:a 2000k -ac 6 -ar 48k -c:a ac3 -map_metadata -1 -movflags +faststart -muxdelay 0 -muxpreload 0 -metadata service_provider="dizqueTV" -metadata service_name="Apartment 5A" -f mpegts pipe:1

**Comment by b3rs3rk** [comment]
Perfect.  disqueTV shows as the service_provider metadata,  I'll add this in the next release.
