### ISSUE TITLE
[ENHANCEMENT] - Add icon for when deepstack GPU docker is running/started

### ISSUE THREAD

**Issue by chillr21** [b3rs3rk/gpustat-unraid#26]
![image](https://user-images.githubusercontent.com/46468853/115539764-780f0380-a2f1-11eb-9ec8-21ac4cf5028b.png)

![image](https://user-images.githubusercontent.com/46468853/115540761-7560de00-a2f2-11eb-863c-64896166af8e.png)

![image](https://user-images.githubusercontent.com/46468853/115540225-fa97c300-a2f1-11eb-91c6-7b8422771e0c.png)

Any chance of adding the deepstack gpu icon when the docker is running?

**Comment by b3rs3rk** [comment]
Does intelligencelayer always signify a deepstack process or do other applications potentially use it?  I'm just trying to avoid adding false detections.

**Comment by chillr21** [comment]
Not sure but think a match on `/app/intelligencelayer/shared` in the context of processes on an unraid server would likely be unique to deepstack running.

**Comment by b3rs3rk** [comment]
Okay.  I'll have to add a bit of code to support it since it won't have 'deepstack' anywhere but not too hard.

**Comment by chillr21** [comment]
Just installed the plugin update, working well - thank you

**Comment by b3rs3rk** [comment]
@chillr21 can I see a snap of the plugin?

**Comment by chillr21** [comment]
Sure -

Idle:
![1](https://user-images.githubusercontent.com/46468853/116013916-cbcd7400-a686-11eb-8ec3-fdd628096dba.png)
Active (post active really):
![2](https://user-images.githubusercontent.com/46468853/116013954-f3244100-a686-11eb-9a20-d6d56db5e36c.png)
Multiple active:
![3](https://user-images.githubusercontent.com/46468853/116013963-ffa89980-a686-11eb-96a1-5ed9506bc2b0.png)

**Comment by b3rs3rk** [comment]
@chillr21 - does deepstack always have a thread running that invokes the GPU and that's why when it is idle it is still detecting it?

**Comment by chillr21** [comment]
Yes detection.py is always active while the deepstack GPU docker is started, the GPU only moves from P8 to P2 state when an image is sent to deepstack to process - it then returns to P8 state after a short period of time.
