### ISSUE TITLE
[ENHANCEMENT] - include Emby icon on dashboard

### ISSUE THREAD

**Issue by guru69** [b3rs3rk/gpustat-unraid#32]
When hardware transcoding Emby icon doesn't show on the dashboard
Process shows in nvidia-smi as _/app/emby/ffmpeg_
![emby-logo](https://user-images.githubusercontent.com/17300382/151732174-14ec0b9e-3187-4812-a6ba-17f037567fd8.png)

**Comment by b3rs3rk** [comment]
This should work for you now, at least with whatever container you are using to report the command line displayed by nvidia-smi.
