### ISSUE TITLE
Nil Tdarr Icon on GPU Stat page on Unraid Dashboard.

### ISSUE THREAD

**Issue by Alphacosmos** [b3rs3rk/gpustat-unraid#37]
**Describe the bug**
Tdarr icon is not displayed on the Unraid WebUI when TDARR is using GPU.

**To Reproduce**
1. Go to Hardware transcode with Tdarr
2. Click on 'Click on Unraid Dashboard
3. Scroll down to 'GPU Stastics
4. See processes running but icon not displayed. 

**Expected behavior**
Tdarr icon to be displayed 

**Screenshots**
![Screenshot 2022-03-31 112921](https://user-images.githubusercontent.com/57428134/160952581-0ab1b935-3d28-4ce1-a6ce-7f9be737b6ef.png)

**Client (please complete the following information):**
 - OS: [Windows 11
 - Browser [Chrome]
 - Version [100.0.4896.60]

**Server (please complete the following information):**
 - Device: [Physical Server]
 - OS Version: [Unraid 6-10-0rc4]
 - GPU: [Nvidia GTX 1080TI ]

**Comment by b3rs3rk** [comment]
@Alphacosmos run ```nvidia-smi``` while tdarr is using the GPU and get me the result.  My guess is that tdarr is just running 'ffmpeg' which cannot be use to positively identify it.  So I can't fix that.

**Comment by Alphacosmos** [comment]
Ran Nvidia-Smi was transcoding as required. Reset Unraid WebUI cache in chrome and icon started working.
