### ISSUE TITLE
Support for Unraid 6.10.x

### ISSUE THREAD

**Issue by pish180** [b3rs3rk/gpustat-unraid#39]
Provide Support for Unraid version 6.10.x

**Comment by b3rs3rk** [comment]
@pish180 I'm using UnRAID 6.10.2 with an NVIDIA GPU and it functions perfectly.  Not sure what support you're asking me to provide.

**Comment by pish180** [comment]
It wasn't working for a while when 6.10 was released.  As you said it seems to be working fine now.
