### ISSUE TITLE
[BUG] - Briefly describe issue here

### ISSUE THREAD

**Issue by Manu-Devloo** [b3rs3rk/gpustat-unraid#55]
**Describe the bug**
Dashboard bug

**To Reproduce**
1. Go to 'Dashboard'

**Expected behavior**
To have it work like the other widgets

**Screenshots**
![image](https://user-images.githubusercontent.com/95429732/225619724-fafdc1b6-482b-4912-80b1-0f1a5204d3fd.png)

**Client (please complete the following information):**
 - OS: [e.g. Windows 7/10, MacOS]
 - Browser Firefox, and other browsers

**Server (please complete the following information):**
 - Device: Phisical server
 - OS Version: v6.12
 - GPU: intel

**Additional context**

**Comment by Xaositek** [comment]
This is fixed by https://github.com/b3rs3rk/gpustat-unraid/pull/52 among with multiple GPU support.

**Comment by Manu-Devloo** [comment]
When will this be added to the main brach?

**Comment by ich777** [comment]
See #56
